### ISSUE TITLE
Sortable Display Grid not working in 1.3

### ISSUE THREAD

**Issue by jwgda** [jquery/jquery-ui#1998]
https://jqueryui.com/sortable/#display-grid

No longer drops into place.

**Comment by mgol** [comment]
PR: #2008.

@borgboyone I'd appreaciate a quick review from you, at least of the source changes (I also added a test) if you have time. I also listed you as a co-author of the PR since source changes have been suggested by you. I hope you're fine with it.

**Comment by mgol** [comment]
jQuery UI 1.13.1 including a fix for this issue has been released: https://blog.jqueryui.com/2022/01/jquery-ui-1-13-1-released/.
