### ISSUE TITLE
draggable + sortable offset is wrong

### ISSUE THREAD

**Issue by barisusakli** [jquery/jquery-ui#2001]
After upgrading from 1.12.1 to 1.13.0 dragging an item to a sortable causes the helper to go out of page when it is over the sortable. 

![](https://i.imgur.com/4Mzz0Gw.gif)

The code to create the draggable is below.

```
	$('#widgets .available-widgets .widget-panel').draggable({
			helper: 'clone',
			distance: 10,
			connectToSortable: '.widget-area',
		});
```
Same code works fine on 1.12.1. Feel free to close if this is already reported since I saw some other issues with draggable on 1.13.0

**Comment by mgol** [comment]
I bisected it to c866e455373028a62a0956455a229fef63e91fac. PR that introduced the regression: #1793.

**Comment by mgol** [comment]
Fix at #2009: restoring one removal from #1793 fixes the issue.

**Comment by mgol** [comment]
jQuery UI 1.13.1 including a fix for this issue has been released: https://blog.jqueryui.com/2022/01/jquery-ui-1-13-1-released/.

**Comment by gaojianzhuang** [comment]
I used the 1.13.1, I have another issue, when drag the element into the iframe and sortable, the cloned element offset change, but end sortable, the offset works again.
![rl6uh-c8xbw](https://user-images.githubusercontent.com/1866009/174605482-88d1e155-a137-44d8-98ba-569e3304414a.gif)

**Comment by mgol** [comment]
@gaojianzhuang This issue is closed. If you have another similar one, please open a new issue and provide a runnable test case without third-party libraries.

**Comment by knockout-componentsprost** [comment]
Found the answer—success!



https://stackdev.space/questions/jquery-draggable-library
