### ISSUE TITLE
jQueryUI 1.13.0 is not published on nuget.org

### ISSUE THREAD

**Issue by auliere** [jquery/jquery-ui#2005]
Hello, jquery-ui community!

We consume jQuery-ui library through a following nuget package - [jQuery.UI.Combined](https://www.nuget.org/packages/jQuery.UI.Combined/) - on my project. However, this package has not been updated recently and it lacks the 1.13.0 version of the library.

We are forced to make an upgrade to 1.13.0 due to a recent security issue found in jquery-ui 1.12.1, however it is impossible to do that via a nuget package right now. 

Could you upload the most recent jquery-ui version as a nuget package, please, if this is possible at all?
Thank you.

**Comment by markvantilburg** [comment]
That package is maintained by outercurve. I have sent (them?) a message on nuget if they could update the package.

**Comment by auliere** [comment]
Thank you very much Mark! Please do send over the response here if you receive any.

**Comment by mgol** [comment]
Migrating to a discussion per @markvantilburg's comment.
