### ISSUE TITLE
Pre-built version of jquery-ui

### ISSUE THREAD

**Issue by MattIPv4** [jquery/jquery-ui#2011]
Hey folks,

We're trying to update jquery-ui on cdnjs, but it looks like this repo as well as the NPM package only distribute jquery-ui in its assorted parts, rather than shipping a pre-built JS bundle like you get if you use the code.jquery.com CDN or the download option on the site.

Is there a distributed version that is pre-built available in an NPM package or tagged git repository anywhere that we can use as the update target for cdnjs? Or, should we just be hosting the content of UI & themes from the NPM package / git repo on the CDN?

Cheers, Matt.

(cc https://github.com/cdnjs/packages/issues/889)

**Comment by mgol** [comment]
Hey! We distribute the built files to CDNs and share zipped copies of the bundles on the jQuery UI sites. We're not planning any changes here as the project is mostly in maintenance mode.

You can download the full source & theme packages by using the quick download links from [the jQuery UI Download Builder page](https://jqueryui.com/download/) or the [1.13 blog post](https://blog.jqueryui.com/2021/10/jquery-ui-1-13-0-released/).

I hope that's enough for you. Thanks!

**Comment by MattIPv4** [comment]
Unfortunately, downloading from the site won't work for cdnjs -- we either need the files in an NPM package, or in a tagged git repo.

Many users rely on jQuery UI through cdnjs, so it'd be great if y'all could help out here so that we can get the updated version made available to them :)

**Comment by mgol** [comment]
How do you handle older jQuery UI versions? I think none of them includes built files, don't they?

**Comment by MattIPv4** [comment]
Looking at our config, we've never updated this library under the new system -- under the old system folks would manually commit files but we no longer permit that for an assortment of reasons (mainly security + infra).

**Comment by glensc** [comment]
you could perhaps create a branch or tag (jquery-ui-1.13.0.cdn) and put built files there for cdnjs...

**Comment by umer936** [comment]
Any chance this is going to happen?

**Comment by mgol** [comment]
Alright, it might be that it's just a question of copying two files from the `dist/cdn` folder before [this line in jquery-release](https://github.com/jquery/jquery-ui/blob/54074fcb1d228ecb06d95362f8db57293d3ba8f4/build/release.js#L134). Since cdnjs is not able to consume what we have right now, let me try this.

If this works (I still need to try it), we could release it as `1.13.2` when it arrives.

**Comment by mgol** [comment]
(please don't assume it will happen just yet, I am not 100% sure yet if this works)

**Comment by mgol** [comment]
PR: #2059

**Comment by mgol** [comment]
@MattIPv4 It might be useful for you to review the above PR as well. This currently adds everything that gets published to the CDN to the `dist` folder. As an example, if this was included in the `1.13.1` release then `dist` in the npm package would contain everything from https://github.com/jquery/codeorigin.jquery.com/tree/main/cdn/ui/1.13.1, maintaining the directory structure. This matters as the CSS files refer to relative image paths, e.g. https://code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css includes `url("images/ui-icons_444444_256x240.png")` which refers to https://code.jquery.com/ui/1.13.1/themes/base/images/ui-icons_444444_256x240.png.

**Comment by MattIPv4** [comment]
👀 That looks/sounds great!

**Comment by MagnonD** [comment]
Looks good to me too
