### ISSUE TITLE
1.13 not compatible with jquery 1.9 due missing $.uniqueSort 

### ISSUE THREAD

**Issue by glensc** [jquery/jquery-ui#2013]
```
Uncaught TypeError: $.uniqueSort is not a function
    at processClassString (jquery-ui.js?id=44a2af31b10434ff00c4:3226)
```

See https://github.com/eventum/eventum/pull/1256,
and https://github.com/eventum/eventum/pull/1240 discussion

But the 1.3.0 release post says jquery 1.8+ remain supported:
> Support for jQuery 1.7 has been dropped; jQuery 1.8 & newer remain supported.
- https://blog.jqueryui.com/2021/10/jquery-ui-1-13-0-released/

**Comment by glensc** [comment]
Seems the compat was added to jquery-1-7.js file:
- https://github.com/jquery/jquery-ui/commit/0b7246b6eeadfa9e2696e22f3230f6452f8129dc

which was later removed

refs:
- https://github.com/jquery/jquery-ui/pull/1773
- https://github.com/jquery/jquery-ui/pull/1801

**Comment by mgol** [comment]
We renamed the file to `jquery-patch.js`; see the relevant portion of [the upgrade guide](https://jqueryui.com/upgrade-guide/1.13/#files-amp-directory-structure).

This should be all you need to let me close the issue. If there's something I missed, please add a comment & I'll reopen. Thanks!
