### ISSUE TITLE
jquery autocomplete custom combobox- ui hangs

### ISSUE THREAD

**Issue by akashdeepjaiswal** [jquery/jquery-ui#2014]
dropdown is too slow to render when data is close 5000. How to limit options like show first 100 data then add option like more data avaible then when clicked on this it bring another 100 and so on

**Comment by mgol** [comment]
Thanks for the report. Does the issue you describe exist when jQuery UI 1.12.1 is used or only with jQuery UI 1.13.0 or newer?

**Comment by noblesigma** [comment]
Even if it's less than 5000, it slows to crawl in the new one. Been using jQuery UI 1.12.1 for years, with a custom thing I wrote; albeit hacky, it does work in 1.12.1 and lags like crazy in 1.13.0 thus we cannot upgrade.

https://github.com/noblesigma/jQuery.UI.Combobox.Lazyload

**Comment by dmethvin** [comment]
Can you provide a link to a simple test case? I'm curious what might have changed.

**Comment by mgol** [comment]
Yes, a test case would definitely help.

**Comment by fnagel** [comment]
This is about the https://api.jqueryui.com/autocomplete/ widget, right?

I don't think this widget is able to work with thousands of options. Not even hundreds. I would strongly recommend to use its AJAX filter functionality.

https://api.jqueryui.com/autocomplete/#option-source
https://jqueryui.com/autocomplete/#remote

**Comment by noblesigma** [comment]
I will try to provide a test case soon. This is definitely a before I had it working now it doesn't work with the new version thing, sorry guys, I know it sucks I just haven't had much time. The github example admittedly is a bit old and it doesn't self host work again, so it will take me some time to make you a new demo.

**Comment by noblesigma** [comment]
https://github.com/noblesigma/jQuery.UI.Combobox.Lazyload/tree/master/example/breakingExample

Sorry it took so long. Good luck. Please let me know if you need help with something.

**Comment by mgol** [comment]
Thanks for the test case! That helps a lot.

I did a performance profile on both 1.12.1 & 1.13.0 test cases and it looks like the performance regression is caused by ef2e9bab92ae898311baa295590cd487d9071319. The added `bindRemoveEvent` function triggers `this._on` calls for all of those elements which takes a lot of time.

**Comment by fnagel** [comment]
@noblesigma Thanks for the test case, I now understand what's the issue here!

@mgol Looks like an ugly bug here as Scott's commit fixed a few bugs. Seems like a complicated one. Not sure what to do :-/

**Comment by mgol** [comment]
I think I have a fix, PTAL: #2037.

**Comment by mgol** [comment]
jQuery UI 1.13.1 including a fix for this issue has been released: https://blog.jqueryui.com/2022/01/jquery-ui-1-13-1-released/.

**Comment by zylenwoodshed768** [comment]
> Yes, a test case would definitely help.





https://terry-rtlcss1.github.io/moralis/
