### ISSUE TITLE
Where is the dist file jquery-ui.min.js?

### ISSUE THREAD

**Issue by jfoclpf** [jquery/jquery-ui#2022]
Stupid question, but I installed this repo via NPM and I want to import it locally.

Where is the file `jquery-ui.min.js` ready to use, that you get for example from [here](https://releases.jquery.com/ui/)?

Normally every npm project has a `dist/` directory from where you can fetch the files ready to use.

**Comment by mgol** [comment]
The file is not in the package, it's only generated to the CDN. I know this is pretty non-standard but we don't have resources to invest in such modifications to the packages so it needs to stay as it is.

**Comment by mgol** [comment]
You can download those files to your project “in a few minutes”. 🤷🏼‍♂️ Or maintain your own clone of jQuery UI that includes it.
