### ISSUE TITLE
Repository / Npm Package doesn't provide dist?

### ISSUE THREAD

**Issue by ellenhutchings** [jquery/jquery-ui#2034]
The NPM package and/or this repo doesn't have the minified jquery-ui js? There's also no documentation on building it manually. What's the point of having an npm is I have to use a manual process to get the complete file?

**Comment by mgol** [comment]
You can use the individual AMD modules from the npm package, that's the main point.

We're unlikely to make changes to the package structure at this stage of the project; see the project status at https://blog.jqueryui.com/2021/10/jquery-maintainers-update-and-transition-jquery-ui-as-part-of-overall-modernization-efforts/.

See also #2022.
