### ISSUE TITLE
jQuery UI Autocomplete widget (version 1.13.0) renders results slower than version 1.12.0

### ISSUE THREAD

**Issue by hptruc** [jquery/jquery-ui#2040]
Hi everyone, @mgol,

I have an issue with the jQuery UI Autocomplete widget after migrating from version 1.12.0 to 1.13.0 to fix security issues. This new version doesn't work smoothly. The results display on the screen slowly and sometimes freeze the UI.

Below is an example that I reproduced to demonstrate the speed difference between the 2 versions of jQuery UI.

- **1.12.0**: https://codepen.io/tructapi/pen/GRMzBwL
- **1.13.0**: https://codepen.io/tructapi/pen/eYGxjXR

The environment and libraries I use:

- Chrome 97.0.4692.71
- jQuery 3.6.0

Steps to reproduce

1. Type a few characters into the textbox and wait for the results to appear.
2. Clear all characters in the textbox by pressing the backspace key on the keyboard.

Result:

- **1.12.0**: the results show up quickly (1-2 seconds) and I can change the characters in the text box to next search.
- **1.13.0**: very slow display results (5-6 seconds), screen freezes and I can't do anything.

Anyone have a solution for this issue? @mgol, I think this is a bug and it affects the user experience.

Many thanks,
Tapi

**Comment by mgol** [comment]
Thanks for the report with a test case!

I hoped it would be related to #2014 which I fixed in #2037 but it looks that the latest development copy still exhibits the issue: https://codepen.io/mgol/pen/dyVagYY.

I'll have a look.

**Comment by mgol** [comment]
Oh, actually, I take that back; the dev copy of jQuery UI hasn't been updated after my PR was merged; I fixed that now. The pen I linked above (https://codepen.io/mgol/pen/dyVagYY) - which uses the dev version of jQuery UI - seems to not have these perf issues.

Can you test with https://releases.jquery.com/git/ui/jquery-ui-git.js and double-check it works fine now? Don't use this copy in production as it can break any time but the current state of that file should be roughly what ends up in 1.13.1 which I plan to release soon if everything goes right.

**Comment by hptruc** [comment]
Thank you very much for your support.

I retested this issue with version [1.13.1-pre](https://releases.jquery.com/git/ui/jquery-ui-git.js) and I have a few comments:

- Result response time has been improved. However, I feel it's still a bit slower than version 1.12.
- UI no longer freezes.

Could you share the release date of version 1.13.1? @mgol 

I migrated the jQuery UI in my project to version 1.13.0 to fix some security issues and I will deploy the patch to production next week.

**Comment by nagyimre1980** [comment]
it would be important to me this week too.  1.13.1 rc1 release?

**Comment by mgol** [comment]
I can’t promise anything but if nothing goes wrong I’m planning to do a `1.13.1` release next week.

**Comment by mgol** [comment]
@hptruc it’s not surprising that it’s slightly slower as #1769 added registration of additional cleanup logic that takes some time; I just optimized that logic in #2037 without changing semantics of it. The 1.12.1 implementation didn’t have this cleanup logic but was leaking memory a lot, causing issues for longer running widgets.

Since there’s no longer a UI freeze, I’m going to close it as a duplicate of #2014. Thanks!
