### ISSUE TITLE
update jquery-ui-dist npm package to 1.13.1

### ISSUE THREAD

**Issue by mikeTWC1984** [jquery/jquery-ui#2044]
Please update jquery-ui-dist npm package to 1.13.1 (it's currently 1.13.0)  Thanks

**Comment by mgol** [comment]
Thanks for the report. However, we only maintain the `jquery-ui` packages on npm & bower, the rest is handled by the community. You need to contact the package maintainer.

**Comment by mgol** [comment]
We don't have the capacity to maintain more packages; I'd recommend to talk to the package maintainer and potentially offer co-maintaining the package if you have time; that way you'll have more influence on the timings.

There's one issue I plan to look at (#2011) which would add at least a base version of the jQuery UI full compiled JS/CSS to the main `jquery-ui` package, maybe with minified versions as well. If that works, it might be enough for many folks.

If you want a small package that doesn't contain the source files but only the built versions then you'll need to reach out to the community about that.
