### ISSUE TITLE
webjar version jquery-ui 1.13.1 not available from maven repositories

### ISSUE THREAD

**Issue by Damnburger** [jquery/jquery-ui#2049]
The maven dependency org.webjars.npm.jquery-ui version 1.13.1 does not seem to have made it to maven repositories.

Does not seem to work.  I think these are provided from https://www.webjars.org/ to maven central, but the latest version seems to have fallen through the cracks.  Not sure if you guys are overly concerned about this delivery mechanism, but I'm sure lots of java devs probably use it as a way to include this library.

**Comment by mgol** [comment]
We only maintain the npm & bower packages, the rest is handled by the community; you'll need to contact whoever is the maintainer of that Maven package.
