### ISSUE TITLE
Different behaviour with autocomplete select v1.12.1 to v1.13.1

### ISSUE THREAD

**Issue by Steve-99** [jquery/jquery-ui#2051]
Using AngularJS and and jQuery 1.12.1 the autocomplete works and the select event fires in every situation that we have.  Updating the jQuery library changes the way autocomplete works and it now only works in some situations.

Using an AngularJS  controller with a view and directive the autocomplete seems to work for both versions of jQuery UI.
When using AngularJS with a controller, view and multiple nested directives, the last directive including the autocomplete control the select event never fires when selecting items with the mouse, using jQuery UI 1.13.1, where it did work with version 1.12.1

Regards
Steve

**Comment by mgol** [comment]
Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) or a similar service? There's not much we can do without it. Thanks!

**Comment by mgol** [comment]
Closing because of a lack of response. We can reopen if needed info is provided.
