### ISSUE TITLE
jQuery.ui draggable is not capable of dragging elements from one browser window to the other?

### ISSUE THREAD

**Issue by Jogii** [jquery/jquery-ui#2073]
### Discussed in https://github.com/jquery/jquery-ui/discussions/2072

<div type='discussions-op-text'>

<sup>Originally posted by **Jogii** May  4, 2022</sup>
Hi all,

I have a use case where i need to drag a element ousite the current browser window. can some suggest how this can be achieved with jquery-ui draggable. I tried setting the appendTo and containment option's to "window". It does not work..  :C</div>

**Comment by mgol** [comment]
Hi! There's no such feature and we're not planning major new features to jQuery UI at the moment.
