### ISSUE TITLE
Is that possible to Using different versions of jQuery and jQuery UI together

### ISSUE THREAD

**Issue by Sukumaran001** [jquery/jquery-ui#2099]
**I have worked the jQuery and jQuery UI with different version, I just using jQuery UI drag the element in mobile view that normally works fine but they conflict issue** 

_jQuery version_ _->3.6.0_ `<script src="../resources/vendors/jquery/jquery-3.6.0.min.js"></script>`
_jQuery UI version ->1.13.1_ `<script src="../resources/vendors/jquery/jquery_UI/jquery-ui.min.js"></script>`

**they have conflict the jquery.min.js 
error:**

```
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example, because scrolling is in progress and cannot be interrupted.

[Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example, because scrolling is in progress and cannot be interrupted.

[Intervention] Ignored attempt to cancel a touchend event with cancelable=false, for example, because scrolling is in progress and cannot be interrupted.

```
### How to Using different versions of jQuery and jQuery UI together?

**Comment by mgol** [comment]
These are browser interventions that limit features of some events in exchange of performance. This is not really related to jQuery or jQuery UI but how you use them. Except for the fact that jQuery doesn't support EventListenerOptions so some of those interventions are not possible to manually reverse with jQuery.

Can you explain what exactly is happening and provide a test case where this can be seen? Also, does the issue appear just with jQuery UI 1.13.1 or with 1.12.1 as well?

**Comment by mgol** [comment]
Closing because of a lack of response. We can reopen if needed info is provided.
