### ISSUE TITLE
Script error for "jquery-patch.js"

### ISSUE THREAD

**Issue by mihaelams1** [jquery/jquery-ui#2107]
I know core.js is deprecated, but until then if one is using individual files as opposed to the bundled version they might encounter an issue in which requirejs can't find jquery-patch:
![image](https://user-images.githubusercontent.com/1153973/182703838-893ab86a-3c05-4b83-8a06-d74b80acb869.png)
This is due to the fact that in [core.js](https://github.com/jquery/jquery-ui/blob/main/ui/core.js) it is referenced as "jquery-patch.js" as opposed to just "jquery-patch":

![image](https://user-images.githubusercontent.com/1153973/182704452-279b5eff-ac4a-4ad9-9b6d-593a5bf08fec.png)

**Comment by mgol** [comment]
Thanks for the report! Fix at #2109.
