### ISSUE TITLE
VSS/Controls/Dialogs whit jQuery UI Widget 1.13.1 error t.uniqueSort is not a function

### ISSUE THREAD

**Issue by miguelo8910** [jquery/jquery-ui#2108]
I find myself using the VSS/Controls/Dialogs in Web Extensión in tfs

`  Dialogs.showMessageDialog("Hello Word");`

When trying to launch the confirmation window the following error is generated
<img width="198" alt="Jquery" src="https://user-images.githubusercontent.com/28771157/183558781-dc285ff8-7d3d-42c3-9d4e-f1598a3f2dc1.png">

in versión jQuery UI Widget 1.11.4 no error is displayed

in versión jQuery UI Widget 1.13.1 error id displayed

Internally the SDK is pointing to the version that fails (https://dev.azure.com/organization/_static/tfs/M208_20220803.13/_scripts/TFS/min/jQueryUI/widget.js), Microsoft recently updated the Jquery UI library but it fails

**Comment by mgol** [comment]
`jQuery.uniqueSort` was added in jQuery 1.12.0 but we're also filling it in for older jQuery versions in https://github.com/jquery/jquery-ui/blob/1.13.2/ui/jquery-patch.js#L36-L40. That file is included in the default build; if you're using a custom one, you need to include it if you use jQuery older than 3.5.0.
