### ISSUE TITLE
JQuery ui min version 1.13.2

### ISSUE THREAD

**Issue by vijay9966** [jquery/jquery-ui#2131]
Hi All,

We are trying to upgrade Jquery UI min to 1.13.2 we are getting attached error. 
We noticed error because of V._data inside function v.cleanData. 
If we change this V._data to V.data then no issue at all. 
Can any one advice is it bug ? if yes will it resolve in future version releases ?

![image](https://user-images.githubusercontent.com/800008/202643517-f8102c1d-e5c1-4b38-9520-beb96d1b480f.png)

Thanks,
Vijaya Krishna.

**Comment by mgol** [comment]
Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) or a similar platform? We can't do much with just a screenshot.

**Comment by mgol** [comment]
Closing for lack of response. We can reopen if a test case is provided.
