### ISSUE TITLE
Datepicker tries to insert ill-formed markup

### ISSUE THREAD

**Issue by ByteEater-pl** [jquery/jquery-ui#2141]
The line `this.dpDiv = datepicker_bindHover( $( "<div id='" + this._mainDivId + "' class='ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all'></div>" ) );` uses apostrophes for attributes which is ill-formed XML and causes an error in XHTML documents. Should be quotes.

**Comment by mgol** [comment]
Thanks for the report. Does the issue you describe exist when jQuery UI 1.12.1 is used or only with jQuery UI 1.13.0 or newer?

Also, please provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output).

**Comment by ByteEater-pl** [comment]
I checked and determined that the same offending line is already in 1.7.0 (the oldest version linked from https://releases.jquery.com/ui/).

And a number of similar ones.

The fix is simple: the attributes in the snippets should be in quotes (`"`), not apostrophes (`'`). I can provide it as a PR if it's tentatively greenlit.

It seems JS Bin doesn't support XHTML, so it's of no use here.

**Comment by ByteEater-pl** [comment]
I encountered this issue when trying to instantiate the Tabs control.

Turns out I can't reproduce it anymore. It seems likely it was in fact a bug in Firefox and has been fixed in the meantime, with a recent update. I'm fine with closing. If it comes back, reopening remains an option.

**Comment by mgol** [comment]
Thanks for the update. In that case, we can close. If you’re able to reproduce, comment here with a test case and we can reopen.
