### ISSUE TITLE
Tooltip show / hide error

### ISSUE THREAD

**Issue by ferpagano** [jquery/jquery-ui#2148]
Hello, 

I'm using pgGrid (v8.7,0) with column validation inside an Angular v13(13.3.12) App. When the validator fires It should show the tooltip but It's throwing a TypeError. The line that has the problem is:
"options.complete = callback;"
The variable "options" is a boolean, and I think problem is related to strict mode because when I tried a similar line without strict mode, it ran fine.

jquery -> v3.4.0
jquery-ui-pack -> v1.12.3

Thanks in advance.
Fernando.

> TypeError: Cannot create property 'complete' on boolean 'true'
> Error:
> core.mjs:7739         
>        ERROR TypeError: Cannot create property 'complete' on boolean 'true'
>     at $.Widget.<computed> [as _show] (jquery-ui.js:716:3)
>     at $.<computed>.<computed>._open (jquery-ui.js:15926:8)
>     at $.<computed>.<computed>._open (jquery-ui.js:139:25)
>     at $.<computed>.<computed>._updateContent (jquery-ui.js:15855:9)
>     at $.<computed>.<computed>._updateContent (jquery-ui.js:139:25)
>     at Object.<anonymous> (jquery-ui.js:15732:10)
>     at Function.each (jquery.js:391:19)
>     at $.<computed>.<computed>._setOption (jquery-ui.js:15731:6)
>     at $.<computed>.<computed>._setOption (jquery-ui.js:139:25)
>     at $.<computed>.<computed>._setOptions (jquery-ui.js:429:9)

jquery-ui.js CODE:
`
$.each( { show: "fadeIn", hide: "fadeOut" }, function( method, defaultEffect ) {
	$.Widget.prototype[ "_" + method ] = function( element, options, callback ) {
		if ( typeof options === "string" ) {
			options = { effect: options };
		}

		var hasOptions;
		var effectName = !options ?
			method :
			options === true || typeof options === "number" ?
				defaultEffect :
				options.effect || defaultEffect;

		options = options || {};
		if ( typeof options === "number" ) {
			options = { duration: options };
		}

		hasOptions = !$.isEmptyObject( options );
		options.complete = callback;

		if ( options.delay ) {
			element.delay( options.delay );
		}

		if ( hasOptions && $.effects && $.effects.effect[ effectName ] ) {
			element[ method ]( options );
		} else if ( effectName !== method && element[ effectName ] ) {
			element[ effectName ]( options.duration, options.easing, callback );
		} else {
			element.queue( function( next ) {
				$( this )[ method ]();
				if ( callback ) {
					callback.call( element[ 0 ] );
				}
				next();
			} );
		}
	};
} );

`

**Comment by mgol** [comment]
Thanks for the report. This has been fixed in #1931 and is present in jQuery UI 1.13.0 or newer.

Please always update to the latest stable version of jQuery UI before submitting an issue. A confusion here might be that the `jquery-ui-pack` package doesn't have any newer version. This package is not maintained by us, though, and it looks unmaintained at the moment. You'll need to switch to the upstream one. Note that it's not exported as a CommonJS module, though.

I'd be fine with adding such a support - PRs welcome if you're interested. It'd most likely need to land in 1.14.0 as it may be breaking in some edge cases.

**Comment by mgol** [comment]
(worth noting is that jQuery UI 1.13 always runs in strict mode)

**Comment by ferpagano** [comment]
Thanks!. Didn't notice jquery-ui-pack was from a different project.
