### ISSUE TITLE
The div of the tooltip made does not disappear when using the tooltip

### ISSUE THREAD

**Issue by jinnnyou** [jquery/jquery-ui#2169]
There is a issue that the div of the tooltip made does not disappear when tooltip is used in the tuigrid.
The version I'm using is v1.12.1, but has it been fixed in the new version?

**Comment by mgol** [comment]
I cannot answer your question; we expect issue reporters to check that by themselves and only open an issue after verifying it hasn't been fixed yet.

Without such information or even a test case, there's not much we can do here so I'm going to close the issue. We can reopen if sufficient information is provided.
