### ISSUE TITLE
Sample code for Dialog is broken

### ISSUE THREAD

**Issue by Hadakajime** [jquery/jquery-ui#2183]
All the samples for each type of Dialog screen here:
https://jqueryui.com/dialog

The main CSS file is incorrectly linked, resulting in the modal not working correctly, such as not being resizable and everything looking wrong.

The HTTP protocol is missing:
`href="//code.jquery.com`
`<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">`

**Comment by fnagel** [comment]
This looks good to me on Windows with latest FF. Can you check again?

Using `//` is just a wildcard for both, `http.//` and `https://`.

**Comment by Hadakajime** [comment]
save the source to a local file and it doesn't work:

![image](https://github.com/jquery/jquery-ui/assets/20448845/416be0d8-e58e-48dd-9fed-4f10b79a1549)

**Comment by markvantilburg** [comment]
firefox tries to load the file with file:// if opened locally

GET file://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css net::ERR_FILE_NOT_FOUND

**Comment by mgol** [comment]
Thanks for the report; fixed in https://github.com/jquery/jqueryui.com/commit/7945c962eeb513a0dd28506bf2f48a3f28a7cd4f. It should be deployed soon.
