### ISSUE TITLE
jQuery 1.14 (jQuery UI 1.13 Upgrade Guide)

### ISSUE THREAD

**Issue by Chealer** [jquery/jquery-ui#2197]
[The _Reminder: API Redesigns_ section of the _jQuery UI 1.13 Upgrade Guide_](https://jqueryui.com/upgrade-guide/1.13/) contains:

> Although the redesigns introduced breaking changes, 1.12 & 1.13 maintains a lot of compatibility with the 1.11 API by default. This is accomplished by rebuilding the 1.11 API on top of the 1.12/1.13 API. The default behavior for all 1.12 & 1.13 releases will be to simultaneously use the 1.11 and 1.12/1.13 APIs where possible. If you would like to load just the 1.12/1.13 API without the 1.11 API to prepare for **jQuery UI 1.14**, you can set the $.uiBackCompat flag to false.

Yet, [the _jQuery maintainers update and transition jQuery UI as part of overall modernization efforts_ blog post](https://blog.jqueryui.com/2021/10/jquery-maintainers-update-and-transition-jquery-ui-as-part-of-overall-modernization-efforts/) contains:

> Today, [jQuery UI announced version 1.13](https://blog.jqueryui.com/2021/10/jquery-ui-1-13-0-released/) — its first release in 5 years and the project’s **final planned release**. [...] jQuery UI is in maintenance-only mode. Users should not expect any new releases, though patches may be issued to resolve critical security, interoperability, or regression bugs. Trac, the project’s bug-tracking tool, has been put in read-only mode and developers are asked to file any critical issues on the project’s [GitHub repository](https://github.com/jquery/jquery-ui/issues).

These quotes are contradictory about whether a 1.14 version of jQuery UI is planned.

**Comment by mgol** [comment]
I think we will release 1.14. This won't be a big release as previous updates were; we'll just focus on whatever is needed to reduce maintenance burden - dropping some browsers & legacy patches, perhaps turning the `$.uiBackCompat` flag to `false` by default, reducing support for compatible jQuery Core releases.

**Comment by Chealer** [comment]
It does!
Thanks a lot Michał, for this and all the rest of the work 👏
