### ISSUE TITLE
Precede the accordion widget with Expand All and Collapse All buttons by default

### ISSUE THREAD

**Issue by CharlesBelov** [jquery/jquery-ui#2201]
The Accordion Widget is set to only have one panel open at a time.

This is a feature request to add expand all and collapse all buttons for site visitors who don't want to engage with an accordion.

I find accordions present accessibility challenges. Specifically, they require too many clicks (physical challenge) and the clicking/reveal/hide is distracting (cognitive challenge). I would rather expand all and scroll up and down as needed.

**Comment by mgol** [comment]
Thanks for the proposal. However, we are not looking into feature requests right now as jQuery UI is in maintenance mode: https://blog.jqueryui.com/2021/10/jquery-maintainers-update-and-transition-jquery-ui-as-part-of-overall-modernization-efforts/.
