### ISSUE TITLE
Set the Accordion Widget to respect prefers-reduced-motion by default

### ISSUE THREAD

**Issue by CharlesBelov** [jquery/jquery-ui#2202]
Currently, site developer has to specifically program the accordion widget API to not animate opening and closing of accordion panels. It would be better if the accordion widget automatically respected prefers-reduced-motion and defaulted to animating only if prefers-reduced-motion is not set to reduce.

**Comment by mgol** [comment]
Thanks for the proposal. However, we are not looking into feature requests right now as jQuery UI is in maintenance mode: https://blog.jqueryui.com/2021/10/jquery-maintainers-update-and-transition-jquery-ui-as-part-of-overall-modernization-efforts/.
