### ISSUE TITLE
Version of jquery in dependencies is malformed?

### ISSUE THREAD

**Issue by SpecialK118** [jquery/jquery-ui#2204]
It looks like the dependent version of jquery is malformed in the `jquery-ui/package.json` file

	"dependencies": {
		"jquery": ">=1.8.0 <4.0.0"
	},

the python package [semantic_version](https://pypi.org/project/semantic-version/) (last version - 2.10.0) is unable to parse it and throws the following error:

    File ".../semantic_version-2.10.0-py3.8.egg/semantic_version/base.py", line 1225, in __init__
      super(LegacySpec, self).__init__(expression)
    File ".../semantic_version-2.10.0-py3.8.egg/semantic_version/base.py", line 647, in __init__
      self.clause = self._parse_to_clause(expression)
    File ".../semantic_version-2.10.0-py3.8.egg/semantic_version/base.py", line 1043, in _parse_to_clause
      return cls.Parser.parse(expression)
    File ".../semantic_version-2.10.0-py3.8.egg/semantic_version/base.py", line 1063, in parse
      raise ValueError("Invalid simple block %r" % block)
     ValueError: Invalid simple block '>=1.8.0<4.0.0'

There are multiple tickets for this in semantic_version package, in which the maintainer claims this is not a valid NPM notation:
https://github.com/rbarrois/python-semanticversion/issues/99
https://github.com/rbarrois/python-semanticversion/issues/127

Could it possibly need to be ">=1.8.0, <4.0.0"?

**Comment by dmethvin** [comment]
It seems okay based on the description at https://github.com/npm/node-semver?tab=readme-ov-file#ranges

> Comparators can be joined by whitespace to form a comparator set, which is satisfied by the intersection of all of the comparators it includes.

If there is a less ambiguous or more authoritative BMF grammar for this, I wasn't able to find it in 30 seconds of searching.

**Comment by mgol** [comment]
The form used in our package.json is actually a normalized form that packages like `semver` use as a base, converting all the other forms to this one.

If you parse this field, make sure to use a tool that understands the semver standard.
