### ISSUE TITLE
Selecting an option from an autocomplete drop list no longer works on Chrome for Android - 1.13

### ISSUE THREAD

**Issue by jamezamm** [jquery/jquery-ui#2207]
After upgrading from 1.12.1 to 1.13.2, selecting an option (by touch) from an autocomplete drop list no longer works on Chrome for Android.

Please note that no errors are displayed within chrome's console, thus leading me to think that no event is being triggered.

Reverting back to 1.12.1 fixed the issue.

**Comment by fnagel** [comment]
Thanks for the bug report. Is this only an issue in Chrome or other browsers too (e.g. FF?). 
Does this occur when using the default demo? https://jqueryui.com/resources/demos/autocomplete/default.html

**Comment by jamezamm** [comment]
Hi. Thanks for the reply. I have tried the default demo and couldn't replicate the issue.

I investigated my code and found out that the issue was occurring when returning false within the select event callback.

Removing that one line of code resolved the issue.

I will be closing the issue since no further action is required,

**Comment by fnagel** [comment]
Glad you were able to fix your issue. And thanks for the feedback!
