### ISSUE TITLE
User is not able to access the “Increment/decrement” hours and minutes button using “TAB” and “ARROWS” in the “Select time” dialogue.

### ISSUE THREAD

**Issue by msftedad** [jquery/jquery-ui#2217]
**Severity:** A11ySev2 

**Environment (OS, Application, Versions):** Chromium Edge Version 122.0.2365.80 (Official build) (64-bit)

**Repro Steps :** 
1.Launch the application using URL: [getdatepicker.com/4/#linked-pickers](https://getdatepicker.com/4/#linked-pickers)
2.“Bootstrap 3 Date picker v4 Docs” screen should open.
3.TAB to “Minimum Setup” button and press ENTER.
4.TAB to "Select time” and press ENTER.
5.“Select time” screen should open.
6.Now press TAB or DOWN arrow keys, observe whether the focus is going to “increment/decrement hours” button or not.

**Actual Results:** 

User is not able to access the “Increment/decrement” hours and minutes button using “TAB” and “ARROWS” in the “Select time” dialogue.

**Expected Results:** 

User should be able to access the “Increment/decrement” hours and minutes button using “TAB” and “ARROWS” in the “Select time” dialogue.

https://github.com/jquery/jquery-ui/assets/93735775/a2d151e4-230e-481a-83b7-0586fe53edd8

**Comment by mgol** [comment]
Thanks for the report. Does the issue you describe exist when jQuery UI 1.12.1 is used or only with jQuery UI 1.13.0 or newer?

**Comment by fnagel** [comment]
Afaics this has nothing to do with the jQuery UI Datepicker but this one: https://github.com/Eonasdan/tempus-dominus

**Comment by mgol** [comment]
Closing per Felix's comment.
