### ISSUE TITLE
Will there be build with jQuery 3.7.1?

### ISSUE THREAD

**Issue by jozefbriss** [jquery/jquery-ui#2219]
I am trying to update jQuery for our project to 3.7.1. and at the same time we are using jquery-ui.

It seems having different jQuery versions, 3.7.1 in the project and 3.7.0. in the jquery-ui  means jquery is bundled twice by webpack and functions added to jquery like scrollParent() from 'jquery-ui/ui/scroll-parent' and not added to 3.7.1 jQuery.

Thanks,
Jozef

**Comment by jozefbriss** [comment]
Removing yarn.lock and running yarn install resolved the problem. Thus jquery-ui with last jquery would still be nice but the problem seems to be elsewhere.

**Comment by mgol** [comment]
jQuery UI doesn't bundle any jQuery version, the entire issue was most likely in your project setup.
