### ISSUE TITLE
Selectmenu click to browser browken

### ISSUE THREAD

**Issue by koreaERP** [jquery/jquery-ui#2243]
https://jqueryui.com/selectmenu/
![제목 없음](https://github.com/jquery/jquery-ui/assets/149133368/c6e15577-d0af-4e8c-837d-c342de5b16b8)
↑ Selectmenu click

![제목 없음](https://github.com/jquery/jquery-ui/assets/149133368/46f10d0d-1320-4c30-8663-a1cc113e12bb)

Occurs in the latest version of browser

error code: STATUS_STACK_OVERFLOW

**Comment by mgol** [comment]
Please check for open issues before opening a new one. This is literally the latest reported issue right now: #2241.
