### ISSUE TITLE
TypeScript types using different package name.

### ISSUE THREAD

**Issue by goldingdamien** [jquery/jquery-ui#2252]
TypeScript types using different package name.

Both the repository and npm package use "jquery-ui":
https://github.com/jquery/jquery-ui
https://www.npmjs.com/package/jquery-ui

However, the types use "jqueryui":
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jqueryui
https://www.npmjs.com/package/@types/jqueryui

This makes it difficult to find and automatically import types for jquery-ui.
Example: https://stackoverflow.com/questions/72396891/typescript-and-jquery-ui-what-am-i-doing-wrong

There is also a package (Last updated 8 years ago at time of posting.) with the same name as those types here:
https://www.npmjs.com/package/jqueryui

Would it be possible to consider changing the name of the types?

**Comment by goldingdamien** [comment]
@dmethvin 

Thank you for your response.
It does not matter so much if those packages are not managed by the jQuery UI team.
The real solution would be to have @types packages that match the package name.
Would the jQuery UI team consider creating TypeScript types below?
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jquery-ui

**Comment by dmethvin** [comment]
Can you ask the DefinitelyTyped group about it? It seems like an alias of the existing types would solve the problem. That's not our repo, and there is only a skeletal jQuery UI team.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues

**Comment by goldingdamien** [comment]
@dmethvin 
OK, I'll check there for now.
Thank you for your time.
