### ISSUE TITLE
glitch terminal

### ISSUE THREAD

**Issue by DrBatson** [jquery/jquery-ui#2272]
My previous login I had set when initially making the website has been disabled and I cannot recall all the files I used or what exactly I input to view each store location bank deposits etc and I need to transfer assets from all of my online accounts into a new account through function controls and collect all my assets from each different webpage online.

**Comment by DrBatson** [comment]
Really everything with ssh sha keys and ids are mine and I need to collect all the assets and transfer funds to new accounts and hide some under different links on glitch and recover previously hidden assets on glitch

**Comment by mgol** [comment]
This is a jQuery UI bug tracker, it has nothing to do with Glitch.
