### ISSUE TITLE
1.13.3 package has inconsisent .js file names

### ISSUE THREAD

**Issue by iliekturtles** [jquery/jquery-ui#2279]
The jQuery.UI.Combined 1.13.3 package has inconsistent `.js` file names.

```
jquery-ui-1-13.3.js
jquery-ui-1.13.3.min.js
```

`jquery-ui-1-13.3.js` should be `jquery-ui-1.13.3.js` -- note the `.` after the major version number instead of a `-`.

**Comment by mgol** [comment]
Is this abut the NuGet package? We don't maintain it - we only publish to npm ourselves; please report such issues to the package maintainer.

**Comment by iliekturtles** [comment]
Yes, the nuget.org package. I followed the "project website" link to get here not realizing you didn't make the nuget.org package. Thanks for letting me know. The link in the readme provided by the package maintainers, https://nugetpackages.codeplex.com/, is dead.

**Comment by mgol** [comment]
It'd be good to get the link to the jQuery UI website removed to not suggest it's an official package. And also to fix the link in README. But you'll need to contact the package maintainers somehow to have it done.

Also, note that [jQuery UI 1.14.0 has been released](https://blog.jqueryui.com/2024/08/jquery-ui-1-14-0-released/) recently and the 1.13.x line no longer receives any support.

**Comment by shreedhark** [comment]
I do not see the nuget packages for v1.14.0, are you no longer publishing nuget packages?

**Comment by mgol** [comment]
We have never provided Nuget packages; they’ve always been maintained by third parties.
