### ISSUE TITLE
NuGet Package for 1.13.3: jQuery UI File Naming (Version Number) Breaks ASP.NET MVC Script Bundling

### ISSUE THREAD

**Issue by helmut-steiner** [jquery/jquery-ui#2284]
I recently upgraded to jQuery UI 1.13 via NuGet in an older client project. Unfortunately everything stopped working as the script file which is automatically placed in the Scripts folder via NuGet has a wrong file naming scheme.
Instead of `jquery-ui-1.13.3.js` the file is named `jquery-ui-1-13.3.js` in the NuGet package.

See:

![image](https://github.com/user-attachments/assets/cf591a28-a4ce-45dc-a957-0ce9b554e15e)

Therefore the bundling in the MVC application doesn't load the file as the naming convention for file versions is broken:

![image](https://github.com/user-attachments/assets/b69351fb-ae31-48ef-a54e-80b440fb00dd)

**Comment by mgol** [comment]
We only maintain the npm package. See #2279.

**Comment by shreedhark** [comment]
I bumped into same issue, sad to see that there is not fix for it :-(

**Comment by shreedhark** [comment]
I do not see the nuget packages for v1.14.0, are you no longer publishing nuget packages?

**Comment by mgol** [comment]
> I do not see the nuget packages for v1.14.0, are you no longer publishing nuget packages?

https://github.com/jquery/jquery-ui/issues/2279#issuecomment-2422898198
