### ISSUE TITLE
Dialog close button missing

### ISSUE THREAD

**Issue by elmervidad99** [jquery/jquery-ui#2288]
Issue related on conflict on bootstrap.bundle.js even if the bootstrap.bundle.js is loaded first before jquery-ui.js

```
<!-- jQuery Library v3.7.1 -->
<script src="js/jquery-ui-1.13.3/external/jquery/jquery-3.7.1.min.js"></script>

<!-- Bootstrap v5.3.3 -->
<link href="vendor/twbs/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"/>
<link href="vendor/twbs/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet"/>
<script src="vendor/twbs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<!-- jQuery UI v1.13.3 -->
<link href="js/jquery-ui-1.13.3/jquery-ui.min.css" rel="stylesheet"/>
<link href="js/jquery-ui-1.13.3/jquery-ui.structure.min.css" rel="stylesheet"/>
<link href="js/jquery-ui-1.13.3/jquery-ui.theme.min.css" rel="stylesheet"/>
<script src="js/jquery-ui-1.13.3/jquery-ui.min.js"></script>
```

![image](https://github.com/user-attachments/assets/31f0a519-a61d-4cad-b9e1-3be053a4d384)

**Comment by elmervidad99** [comment]
sorry my bad, got the solution again :)

$(document).ready(function() {
      var bootstrapButton = $.fn.button.noConflict()
      $.fn.bootstrapBtn = bootstrapButton;
      
      // other codes
});

**Comment by mgol** [comment]
If an issue you reported turns out to not be valid, please close it so that we don't have to.
