### ISSUE TITLE
Uncaught TypeError: this._bindFormResetHandler is not a function

### ISSUE THREAD

**Issue by apausepi** [jquery/jquery-ui#2290]
Hello,

**How to reproduce :** 

I use this code : 
`$("#inclbreakfastchoice").selectmenu();`

And template
```
              <select data-original-title="Calculation will include the breakfast impact if Incl. Breakfast is selected" id="inclbreakfastchoice" class="form-control" data-toggle="tooltip" data-placement="bottom" title="">
                    <option value="0" >Excl. Breakfast</option>
                    <option value="1" selected="selected">Incl. Breakfast</option>
                </select>
```
**Result :** 

Uncaught TypeError: this._bindFormResetHandler is not a function
https://github.com/jquery/jquery-ui/blob/54f96eea31b21d9ecb00912261df3e5aaebf8cce/ui/widgets/selectmenu.js#L84

Someone have an idea ?

**Comment by mgol** [comment]
The method is defined in `form-reset-mixin`, you may be missing this module (it's in dependencies of `selectmenu`).

I'm going to close since this seems to not be an error in jQuery UI code.

**Comment by apausepi** [comment]
Thanks for you answere.
